from __future__ import annotations

from typing import Any


def demo_events() -> list[dict[str, Any]]:
    return [
        {
            "schema_version": "v1",
            "event_id": 1001,
            "session_id": 501,
            "event_seq": 1001,
            "session_seq": 1,
            "phase": "http.request",
            "transport": "http",
            "direction": "out",
            "method": "POST",
            "url": "/v1/messages",
            "domain": "api.anthropic.com",
            "status": None,
            "action": "request",
            "content_type": "application/json",
            "traffic_class": "model_http",
            "req_headers": [
                {"name": "content-type", "value": "application/json"},
                {"name": "x-client", "value": "codex"},
            ],
            "resp_headers": [],
            "req_body": {
                "bytes": 176,
                "text": '{"model":"claude-3-5-sonnet","max_tokens":64,"messages":[{"role":"user","content":"Summarize the deployment plan and mention rollback."}]}',
                "truncated": False,
            },
            "resp_body": None,
            "primary_text": "Summarize the deployment plan and mention rollback.",
            "preview": '{"model":"claude-3-5-sonnet","max_tokens":64,"messages":[{"role":"user","content":"Summarize the deployment plan ...',
        },
        {
            "schema_version": "v1",
            "event_id": 1002,
            "session_id": 501,
            "event_seq": 1002,
            "session_seq": 2,
            "phase": "http.response",
            "transport": "http",
            "direction": "in",
            "method": "POST",
            "url": "/v1/messages",
            "domain": "api.anthropic.com",
            "status": 200,
            "action": "response",
            "content_type": "application/json",
            "traffic_class": "model_http",
            "req_headers": [],
            "resp_headers": [
                {"name": "content-type", "value": "application/json"},
                {"name": "server", "value": "cloudflare"},
            ],
            "req_body": None,
            "resp_body": {
                "bytes": 208,
                "text": '{"id":"msg_01","type":"message","content":[{"type":"text","text":"Deploy in two stages. Keep a rollback tag and revert target ready before migration."}]}',
                "truncated": False,
            },
            "primary_text": "Deploy in two stages. Keep a rollback tag and revert target ready before migration.",
            "preview": '{"id":"msg_01","type":"message","content":[{"type":"text","text":"Deploy in two stages. Keep a rollback tag ...',
        },
        {
            "schema_version": "v1",
            "event_id": 1003,
            "session_id": 777,
            "event_seq": 1003,
            "session_seq": 1,
            "phase": "ws.message.out",
            "transport": "ws",
            "direction": "out",
            "method": "GET",
            "url": "/backend-api/codex/responses",
            "domain": "chatgpt.com",
            "status": None,
            "action": "request",
            "content_type": "application/json",
            "traffic_class": "model_ws",
            "req_headers": [{"name": "upgrade", "value": "websocket"}],
            "resp_headers": [],
            "req_body": {
                "bytes": 219,
                "text": '{"type":"response.create","response":{"instructions":"Review this Rust patch and only mention real regressions.","metadata":{"repo":"agent-shield"}}}',
                "truncated": False,
            },
            "resp_body": None,
            "primary_text": "Review this Rust patch and only mention real regressions.",
            "preview": '{"type":"response.create","response":{"instructions":"Review this Rust patch and only mention real regressions."}}',
        },
        {
            "schema_version": "v1",
            "event_id": 1004,
            "session_id": 777,
            "event_seq": 1004,
            "session_seq": 2,
            "phase": "ws.message.in",
            "transport": "ws",
            "direction": "in",
            "method": "GET",
            "url": "/backend-api/codex/responses",
            "domain": "chatgpt.com",
            "status": None,
            "action": "response",
            "content_type": "application/json",
            "traffic_class": "model_ws",
            "req_headers": [],
            "resp_headers": [],
            "req_body": None,
            "resp_body": {
                "bytes": 198,
                "text": '{"type":"response.output_text.delta","delta":"Potential issue: the new listener dashboard stores column widths in localStorage but does not clamp on hidden columns."}',
                "truncated": False,
            },
            "primary_text": "Potential issue: the new listener dashboard stores column widths in localStorage but does not clamp on hidden columns.",
            "preview": '{"type":"response.output_text.delta","delta":"Potential issue: the new listener dashboard stores column widths ...',
        },
        {
            "schema_version": "v1",
            "event_id": 1005,
            "session_id": 880,
            "event_seq": 1005,
            "session_seq": 1,
            "phase": "sse.event.in",
            "transport": "sse",
            "direction": "in",
            "method": "POST",
            "url": "/v1internal:streamGenerateContent?alt=sse",
            "domain": "cloudcode-pa.googleapis.com",
            "status": 200,
            "action": "response",
            "content_type": "text/event-stream",
            "traffic_class": "model_http",
            "req_headers": [],
            "resp_headers": [{"name": "content-type", "value": "text/event-stream"}],
            "req_body": None,
            "resp_body": {
                "bytes": 164,
                "text": 'data: {"candidates":[{"content":{"parts":[{"text":"Plan: build, smoke test, deploy canary, then widen rollout."}]}}]}',
                "truncated": False,
            },
            "primary_text": "Plan: build, smoke test, deploy canary, then widen rollout.",
            "preview": 'data: {"candidates":[{"content":{"parts":[{"text":"Plan: build, smoke test, deploy canary, then widen rollout."}]}}]}',
        },
    ]
